// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znnrjwwqzpqqgezlgdxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpubnJqd3dxenBxcWdlemxnZHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNzg2MzIsImV4cCI6MjA2OTg1NDYzMn0.fXCRrpOK6IDuGUENwPJ9cOp4ZLMqdXfn9ud0u4CcVoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});